In [137]:
import numpy as np

# (#1) Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

# Створення масиву з першими 10-ма натуральними числами за допомогою NumPy
natural_numbers = np.arange(1, 11)

# Виведення значень масиву
print(natural_numbers)
      

[ 1  2  3  4  5  6  7  8  9 10]


In [138]:
# (#2) Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

# Створення двовимірної матриці розміром 3*3, заповненої нулями.
matrix = np.zeros((3, 3))

# Виведення значень матриці.
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [139]:
# (#3) Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

# Розмірність таблиці
rows = 5
cols = 5

# Створення масиву розміром 5*5 з випадковими цілими числами від 1 до 10.
matrix = np.random.randint(1, 11, size=(rows, cols))

# Виведення значень масиву.
print(matrix)

[[ 1  5  9  1  6]
 [ 5  3  3  7  3]
 [ 3 10  8  9  6]
 [ 6  6  2  1  4]
 [10  7  4  5  1]]


In [140]:
# (#4) Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

# Розмірність матриці.
rows = 4
cols = 4

# Створення масиву 4*4 з випадковими дійсними числами від 0 до 1.
matrix = np.random.rand(rows, cols)

# Виведення значень масиву.
print(matrix)

[[0.59505782 0.77432755 0.21118354 0.37253269]
 [0.33043218 0.4818018  0.42192799 0.80134902]
 [0.07747665 0.24346846 0.15133449 0.65275485]
 [0.24162423 0.51376412 0.45188711 0.19917088]]


In [141]:
# (#5) Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

# Розмірність масиву.
size = 5

# Створення двох масивів розміром 5, з випадковими цілими числами від 1 до 10.
array1 = np.random.randint(1, 11, size= size)
array2 = np.random.randint(1, 11, size=size)

print("Масив 1", array1)
print("Масив 2", array2)

# Поелементне додавання
sum_result = array1 + array2
print("Додавання", sum_result)

# Поелементне віднімання
subtract_result = array1 - array2
print("Віднімння", subtract_result)

# Поелементне множення
multiply_result = array1 * array2
print("Множення", multiply_result)

Масив 1 [ 1  3  1 10  3]
Масив 2 [5 5 8 6 8]
Додавання [ 6  8  9 16 11]
Віднімння [-4 -2 -7  4 -5]
Множення [ 5 15  8 60 24]


In [142]:
# (#6) Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

# Розмірність векторів
size = 7

# Створення двох векторів з довільними числами.
vector1 = np.random.rand(size)
vector2 = np.random.rand(size)

# Знаходження скалярного добутку.
dot_product = np.dot(vector1, vector2)

print("Вектор 1", vector1)
print("Вектор 2", vector2)
print("Скалярний добуток: ", dot_product)

Вектор 1 [0.66926096 0.9159719  0.12683558 0.68725573 0.66319776 0.89872114
 0.48590054]
Вектор 2 [0.92685842 0.88085973 0.01206794 0.96911668 0.43555267 0.44801802
 0.59096105]
Скалярний добуток:  3.0733636688224624


In [143]:
# (#7) Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

# Розмірності матриць.
rows1, cols1 = 2, 2
rows2, cols2 = 2, 3

# Створення двох матриць з випадковими цілими числами від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(rows1, rows1))
matrix2 = np.random.randint(1, 11, size=(rows2, rows2))

# Перемноження матриць.
product =np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)

print("Результат перемноження:")
print(product)

Матриця 1:
[[9 7]
 [7 8]]
Матриця 2:
[[2 9]
 [2 7]]
Результат перемноження:
[[ 32 130]
 [ 30 119]]


In [144]:
# (#8) Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

# # Створення випадкової матриці розміром 3x3 з цілими числами в діапазоні від 1 до 10.
random_matrix =np.random.randint(1, 11, size=(3, 3))

print("Випадкова матриця:")
print(random_matrix)

# Знаходження оберненої матриці.
inverse_matrix = np.linalg.inv(random_matrix)

print("Обернена матриця:")
print(inverse_matrix)

Випадкова матриця:
[[10  3  7]
 [ 7  5  6]
 [ 4  9  8]]
Обернена матриця:
[[-0.21538462  0.6        -0.26153846]
 [-0.49230769  0.8        -0.16923077]
 [ 0.66153846 -1.2         0.44615385]]


In [145]:
# (#9) Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

# Створення випадкової матриці розміром 4x4 з дійсними числами в діапазоні від 0 до 1.
random_matrix = np.random.rand(4, 4)

print("Випадкова матриця:")
print(random_matrix)

# Транспонування матриці.
transposed_matrix = np.transpose(random_matrix)
# Або коротший запис : transposed_matrix = random_matrix.T

print("Транспонована матриця:")
print(transposed_matrix)

Випадкова матриця:
[[0.64029969 0.51527223 0.63110448 0.9114578 ]
 [0.58672399 0.88731154 0.14903859 0.81408958]
 [0.40014367 0.4229834  0.14634872 0.71361905]
 [0.32222972 0.34113611 0.16860173 0.9797964 ]]
Транспонована матриця:
[[0.64029969 0.58672399 0.40014367 0.32222972]
 [0.51527223 0.88731154 0.4229834  0.34113611]
 [0.63110448 0.14903859 0.14634872 0.16860173]
 [0.9114578  0.81408958 0.71361905 0.9797964 ]]


In [146]:
# (#10) Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

# Створення випадкової матриці розміром 3x4 з цілими числами в діапазоні від 1 до 10.
random_matrix = np.random.randint(1, 11, size=(3, 4))
print("Випадкова матриця:")
print(random_matrix)

# Створення випадкового вектора розміром 4 з цілими числами в діапазоні від 1 до 10.
random_vector = np.random.randint(1, 11, size=4)
print("Випадковий вектор:")
print(random_vector)

# Перемноження матриці на вектор.
result = np.dot(random_matrix, random_vector)
# Або коротший запис: result = random_matrix @ random_vector
print("Результат перемноження матриці на вектор:")
print(result)

Випадкова матриця:
[[ 5  1  4  8]
 [ 7 10  6  3]
 [10  9  4 10]]
Випадковий вектор:
[10  8  4  8]
Результат перемноження матриці на вектор:
[138 198 268]


In [147]:
# (#11) Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

# Створення випадкової матриці розміром 2x3 з дійсними числами в діапазоні від 0 до 1.
random_matrix =np.random.rand(2, 3)
print("Випадкова матриця:")
print(random_matrix)

# Створення випадкового вектора розміром 3 з дійсними числами в діапазоні від 0 до 1.
random_vector = np.random.rand(3)
print("Випадковий вектор:")
print(random_vector)

# Перемноження матриці на вектор.
result = np.dot(random_matrix, random_vector)
# Або коротший запис: result = random_matrix @ random_vector

print("Результат перемноження матриці на вектор:")
print(result)

Випадкова матриця:
[[0.76531724 0.20798792 0.84172973]
 [0.72580881 0.72281121 0.46006343]]
Випадковий вектор:
[0.56997667 0.39517471 0.03875132]
Результат перемноження матриці на вектор:
[0.55102267 0.71715885]


In [148]:
# (#12) Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

# Створення двох випадкових матриць розміром 2x2 з цілими числами в діапазоні від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша випадкова матриця:")
print(matrix1)
print("Друга випадкова матриця:")
print(matrix2)

# Поелементне множення матриць.
elementwise_product =np.multiply(matrix1, matrix2)

print("Результат поелементного множення матриць:")
print(elementwise_product)

Перша випадкова матриця:
[[7 1]
 [4 7]]
Друга випадкова матриця:
[[2 5]
 [6 4]]
Результат поелементного множення матриць:
[[14  5]
 [24 28]]


In [149]:
# (#13) Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

# Створення двох матриць 2*2 з випадковими цілими числами від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша випадкова матриця:")
print(matrix1)
print("Друга випадкова матриця:")
print(matrix2)

# Знаходження добутку матриць.
matrix_product = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(matrix_product)

Перша випадкова матриця:
[[4 8]
 [1 7]]
Друга випадкова матриця:
[[1 7]
 [6 6]]
Добуток матриць:
[[52 76]
 [43 49]]


In [150]:
# (#14) Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

# Створення матриці розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 100.
matrix = np.random.randint(1, 101, size=(5, 5))

print("Випадкова матриця:")
print(matrix)

# Знаходження суми елементів матриці.
matrix_sum = np.sum(matrix)

print("Сума елементів матриці:")
print(matrix_sum)

Випадкова матриця:
[[98 44  2 99 10]
 [99 98  3 56 28]
 [66 23 25 15 64]
 [16 55 66 40 61]
 [ 1  6 28 40 60]]
Сума елементів матриці:
1103


In [151]:
# (#15) Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

# Створення двох матриць розміром 4x4 з випадковими цілими числами в діапазоні від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Перша випадкова матриця:")
print(matrix1)
print("Друга випадкова матриця:")
print(matrix2)

# Знаходження різниці матриць.
matrix_difference = np.subtract(matrix1, matrix2)

print("Різниця матриць:")
print(matrix_difference)

Перша випадкова матриця:
[[10  9 10  9]
 [10  2  9  8]
 [ 6  9  5  6]
 [ 7  7  4 10]]
Друга випадкова матриця:
[[ 8  1  7  9]
 [ 5  7  7  3]
 [ 1  3  4  9]
 [ 2 10  2 10]]
Різниця матриць:
[[ 2  8  3  0]
 [ 5 -5  2  5]
 [ 5  6  1 -3]
 [ 5 -3  2  0]]


In [152]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

# Створення випадкової матриці розміром 3x3 з дійсними числами в діапазоні від 0 до 1.
matrix = np.random.rand(3, 3)
print("Випадкова матриця:")
print(matrix)

# Знаходження вектора-стовпчика з сумами елементів кожного рядка матриці.
row_sums = np.sum(matrix, axis=1)

print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(row_sums)

Випадкова матриця:
[[0.6248904  0.21851362 0.33881896]
 [0.32322716 0.57243807 0.45602272]
 [0.48895565 0.55392228 0.85625232]]
Вектор-стовпчик з сумами елементів кожного рядка:
[1.18222298 1.35168795 1.89913025]


In [153]:
# (#17) Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

# Створення матриці розміром 3x4 з довільними цілими числами.
original_matrix = np.random.randint(1, 11, size=(3, 4))
print("Початкова матриця:")
print(original_matrix)

# Створення матриці з квадратами чисел поелементно.
squared_matrix = np.square(original_matrix)

print("Матриця з квадратами чисел:")
print(squared_matrix)

Початкова матриця:
[[ 9  7  1  1]
 [10  3  1  8]
 [ 5  8  2 10]]
Матриця з квадратами чисел:
[[ 81  49   1   1]
 [100   9   1  64]
 [ 25  64   4 100]]


In [154]:
# (#18) Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

# Створення випадкового вектора розміром 4 з цілими числами в діапазоні від 1 до 50.
original_vector =np.random.randint(1, 51, size=4)
print("Початкова вектор:")
print(original_vector)

# Знаходження вектора з квадратними коренями чисел.
sqrt_vector = np.sqrt(original_vector)

print("Вектор з квадратними коренями чисел:")
print(sqrt_vector)

Початкова вектор:
[ 8 19 32 12]
Вектор з квадратними коренями чисел:
[2.82842712 4.35889894 5.65685425 3.46410162]
