In [155]:
import numpy as np

# (#1) Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

# Створення масиву з першими 10-ма натуральними числами за допомогою NumPy
natural_numbers = np.arange(1, 11)

# Виведення значень масиву
print(natural_numbers)
      

[ 1  2  3  4  5  6  7  8  9 10]


In [156]:
# (#2) Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

# Створення двовимірної матриці розміром 3*3, заповненої нулями.
matrix = np.zeros((3, 3))

# Виведення значень матриці.
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [157]:
# (#3) Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

# Розмірність таблиці
rows = 5
cols = 5

# Створення масиву розміром 5*5 з випадковими цілими числами від 1 до 10.
matrix = np.random.randint(1, 11, size=(rows, cols))

# Виведення значень масиву.
print(matrix)

[[ 4  8  7  9  9]
 [10  5  9  8  7]
 [ 7  6  6  1  7]
 [10  5  1  7  4]
 [ 6  2  2  7  5]]


In [158]:
# (#4) Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

# Розмірність матриці.
rows = 4
cols = 4

# Створення масиву 4*4 з випадковими дійсними числами від 0 до 1.
matrix = np.random.rand(rows, cols)

# Виведення значень масиву.
print(matrix)

[[0.88190373 0.28231059 0.98569968 0.65508861]
 [0.53909389 0.84982132 0.14010595 0.25492049]
 [0.22305027 0.66823364 0.54107755 0.13694673]
 [0.8634872  0.39895497 0.73821275 0.8048945 ]]


In [159]:
# (#5) Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

# Розмірність масиву.
size = 5

# Створення двох масивів розміром 5, з випадковими цілими числами від 1 до 10.
array1 = np.random.randint(1, 11, size= size)
array2 = np.random.randint(1, 11, size=size)

print("Масив 1", array1)
print("Масив 2", array2)

# Поелементне додавання
sum_result = array1 + array2
print("Додавання", sum_result)

# Поелементне віднімання
subtract_result = array1 - array2
print("Віднімння", subtract_result)

# Поелементне множення
multiply_result = array1 * array2
print("Множення", multiply_result)

Масив 1 [4 7 3 9 5]
Масив 2 [3 8 4 3 9]
Додавання [ 7 15  7 12 14]
Віднімння [ 1 -1 -1  6 -4]
Множення [12 56 12 27 45]


In [160]:
# (#6) Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

# Розмірність векторів
size = 7

# Створення двох векторів з довільними числами.
vector1 = np.random.rand(size)
vector2 = np.random.rand(size)

# Знаходження скалярного добутку.
dot_product = np.dot(vector1, vector2)

print("Вектор 1", vector1)
print("Вектор 2", vector2)
print("Скалярний добуток: ", dot_product)

Вектор 1 [0.30079397 0.12374764 0.99308171 0.13863751 0.5756743  0.10756359
 0.60702202]
Вектор 2 [0.81772541 0.10966768 0.32904081 0.56549091 0.75879439 0.69644588
 0.30785681]
Скалярний добуток:  1.363307158719777


In [161]:
# (#7) Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

# Розмірності матриць.
rows1, cols1 = 2, 2
rows2, cols2 = 2, 3

# Створення двох матриць з випадковими цілими числами від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(rows1, rows1))
matrix2 = np.random.randint(1, 11, size=(rows2, rows2))

# Перемноження матриць.
product =np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)

print("Результат перемноження:")
print(product)

Матриця 1:
[[10  1]
 [ 4  6]]
Матриця 2:
[[7 7]
 [1 9]]
Результат перемноження:
[[71 79]
 [34 82]]


In [162]:
# (#8) Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

# # Створення випадкової матриці розміром 3x3 з цілими числами в діапазоні від 1 до 10.
random_matrix =np.random.randint(1, 11, size=(3, 3))

print("Випадкова матриця:")
print(random_matrix)

# Знаходження оберненої матриці.
inverse_matrix = np.linalg.inv(random_matrix)

print("Обернена матриця:")
print(inverse_matrix)

Випадкова матриця:
[[6 4 8]
 [4 7 1]
 [6 2 1]]
Обернена матриця:
[[-0.02136752 -0.05128205  0.22222222]
 [-0.00854701  0.17948718 -0.11111111]
 [ 0.14529915 -0.05128205 -0.11111111]]


In [163]:
# (#9) Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

# Створення випадкової матриці розміром 4x4 з дійсними числами в діапазоні від 0 до 1.
random_matrix = np.random.rand(4, 4)

print("Випадкова матриця:")
print(random_matrix)

# Транспонування матриці.
transposed_matrix = np.transpose(random_matrix)
# Або коротший запис : transposed_matrix = random_matrix.T

print("Транспонована матриця:")
print(transposed_matrix)

Випадкова матриця:
[[0.4278098  0.43834839 0.44169023 0.41723827]
 [0.7700982  0.73443257 0.82530558 0.32101662]
 [0.5761508  0.78071392 0.17888102 0.50724443]
 [0.5860689  0.28592783 0.71926156 0.98227592]]
Транспонована матриця:
[[0.4278098  0.7700982  0.5761508  0.5860689 ]
 [0.43834839 0.73443257 0.78071392 0.28592783]
 [0.44169023 0.82530558 0.17888102 0.71926156]
 [0.41723827 0.32101662 0.50724443 0.98227592]]


In [164]:
# (#10) Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

# Створення випадкової матриці розміром 3x4 з цілими числами в діапазоні від 1 до 10.
random_matrix = np.random.randint(1, 11, size=(3, 4))
print("Випадкова матриця:")
print(random_matrix)

# Створення випадкового вектора розміром 4 з цілими числами в діапазоні від 1 до 10.
random_vector = np.random.randint(1, 11, size=4)
print("Випадковий вектор:")
print(random_vector)

# Перемноження матриці на вектор.
result = np.dot(random_matrix, random_vector)
# Або коротший запис: result = random_matrix @ random_vector
print("Результат перемноження матриці на вектор:")
print(result)

Випадкова матриця:
[[1 5 1 7]
 [9 8 4 5]
 [1 8 6 7]]
Випадковий вектор:
[10  8  9 10]
Результат перемноження матриці на вектор:
[129 240 198]


In [165]:
# (#11) Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

# Створення випадкової матриці розміром 2x3 з дійсними числами в діапазоні від 0 до 1.
random_matrix =np.random.rand(2, 3)
print("Випадкова матриця:")
print(random_matrix)

# Створення випадкового вектора розміром 3 з дійсними числами в діапазоні від 0 до 1.
random_vector = np.random.rand(3)
print("Випадковий вектор:")
print(random_vector)

# Перемноження матриці на вектор.
result = np.dot(random_matrix, random_vector)
# Або коротший запис: result = random_matrix @ random_vector

print("Результат перемноження матриці на вектор:")
print(result)

Випадкова матриця:
[[0.37022893 0.0153757  0.3193416 ]
 [0.85451931 0.5302295  0.81290714]]
Випадковий вектор:
[0.92303278 0.65067477 0.06274474]
Результат перемноження матриці на вектор:
[0.37177503 1.18476194]


In [166]:
# (#12) Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

# Створення двох випадкових матриць розміром 2x2 з цілими числами в діапазоні від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша випадкова матриця:")
print(matrix1)
print("Друга випадкова матриця:")
print(matrix2)

# Поелементне множення матриць.
elementwise_product =np.multiply(matrix1, matrix2)

print("Результат поелементного множення матриць:")
print(elementwise_product)

Перша випадкова матриця:
[[ 9 10]
 [ 5 10]]
Друга випадкова матриця:
[[5 1]
 [7 4]]
Результат поелементного множення матриць:
[[45 10]
 [35 40]]


In [167]:
# (#13) Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

# Створення двох матриць 2*2 з випадковими цілими числами від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print("Перша випадкова матриця:")
print(matrix1)
print("Друга випадкова матриця:")
print(matrix2)

# Знаходження добутку матриць.
matrix_product = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(matrix_product)

Перша випадкова матриця:
[[9 4]
 [3 9]]
Друга випадкова матриця:
[[6 3]
 [7 7]]
Добуток матриць:
[[82 55]
 [81 72]]


In [168]:
# (#14) Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

# Створення матриці розміром 5x5 з випадковими цілими числами в діапазоні від 1 до 100.
matrix = np.random.randint(1, 101, size=(5, 5))

print("Випадкова матриця:")
print(matrix)

# Знаходження суми елементів матриці.
matrix_sum = np.sum(matrix)

print("Сума елементів матриці:")
print(matrix_sum)

Випадкова матриця:
[[75 57 93 73 80]
 [ 8 95 33 97 71]
 [ 2 98 94 43 47]
 [88 78 84 19 66]
 [42 28 24 25 96]]
Сума елементів матриці:
1516


In [169]:
# (#15) Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

# Створення двох матриць розміром 4x4 з випадковими цілими числами в діапазоні від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Перша випадкова матриця:")
print(matrix1)
print("Друга випадкова матриця:")
print(matrix2)

# Знаходження різниці матриць.
matrix_difference = np.subtract(matrix1, matrix2)

print("Різниця матриць:")
print(matrix_difference)

Перша випадкова матриця:
[[ 7  4  7  6]
 [10  3  7  1]
 [ 9  3  6  8]
 [ 9  4 10  7]]
Друга випадкова матриця:
[[10  6 10  2]
 [ 9  7  4 10]
 [10  7  9  8]
 [ 5  6  6  2]]
Різниця матриць:
[[-3 -2 -3  4]
 [ 1 -4  3 -9]
 [-1 -4 -3  0]
 [ 4 -2  4  5]]


In [170]:
# (#16) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

# Створення випадкової матриці розміром 3x3 з дійсними числами в діапазоні від 0 до 1.
matrix = np.random.rand(3, 3)
print("Випадкова матриця:")
print(matrix)

# Знаходження вектора-стовпчика з сумами елементів кожного рядка матриці.
row_sums = np.sum(matrix, axis=1)

# Використання reshape() для отримання вектора-стопчика.
column_vektor = row_sums.reshape(-1, 1)

print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(column_vektor)

Випадкова матриця:
[[0.1420733  0.01526829 0.12231383]
 [0.55893116 0.5529427  0.85806769]
 [0.25342561 0.94785907 0.54362164]]
Вектор-стовпчик з сумами елементів кожного рядка:
[[0.27965543]
 [1.96994156]
 [1.74490632]]


In [171]:
# (#17) Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

# Створення матриці розміром 3x4 з довільними цілими числами.
original_matrix = np.random.randint(1, 11, size=(3, 4))
print("Початкова матриця:")
print(original_matrix)

# Створення матриці з квадратами чисел поелементно.
squared_matrix = np.square(original_matrix)

print("Матриця з квадратами чисел:")
print(squared_matrix)

Початкова матриця:
[[9 6 6 1]
 [8 9 2 3]
 [9 2 6 2]]
Матриця з квадратами чисел:
[[81 36 36  1]
 [64 81  4  9]
 [81  4 36  4]]


In [172]:
# (#18) Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

# Створення випадкового вектора розміром 4 з цілими числами в діапазоні від 1 до 50.
original_vector =np.random.randint(1, 51, size=4)
print("Початкова вектор:")
print(original_vector)

# Знаходження вектора з квадратними коренями чисел.
sqrt_vector = np.sqrt(original_vector)

print("Вектор з квадратними коренями чисел:")
print(sqrt_vector)

Початкова вектор:
[44 25 39 35]
Вектор з квадратними коренями чисел:
[6.63324958 5.         6.244998   5.91607978]
