In [58]:
import numpy as np

# (#1) Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

# Створення масиву з першими 10-ма натуральними числами за допомогою NumPy
natural_numbers = np.arange(1, 11)

# Виведення значень масиву
print(natural_numbers)
      

[ 1  2  3  4  5  6  7  8  9 10]


In [59]:
# (#2) Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

# Створення двовимірної матриці розміром 3*3, заповненої нулями.
matrix = np.zeros((3, 3))

# Виведення значень матриці.
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [60]:
# (#3) Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

# Розмірність таблиці
rows = 5
cols = 5

# Створення масиву розміром 5*5 з випадковими цілими числами від 1 до 10.
matrix = np.random.randint(1, 11, size=(rows, cols))

# Виведення значень масиву.
print(matrix)

[[ 2  1  2  3  4]
 [ 8  9  6  3  5]
 [10 10  9  2  5]
 [ 7  5  6  2 10]
 [ 8  7  9  1  8]]


In [61]:
# (#4) Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

# Розмірність матриці.
rows = 4
cols = 4

# Створення масиву 4*4 з випадковими дійсними числами від 0 до 1.
matrix = np.random.rand(rows, cols)

# Виведення значень масиву.
print(matrix)

[[0.58098298 0.58915451 0.68042716 0.9964032 ]
 [0.19734104 0.90114728 0.14853016 0.52149701]
 [0.72572361 0.55034706 0.80886471 0.32453669]
 [0.35307852 0.14716573 0.14143032 0.73279654]]


In [62]:
# (#5) Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

# Розмірність масиву.
size = 5

# Створення двох масивів розміром 5, з випадковими цілими числами від 1 до 10.
array1 = np.random.randint(1, 11, size= size)
array2 = np.random.randint(1, 11, size=size)

print("Масив 1", array1)
print("Масив 2", array2)

# Поелементне додавання
sum_result = array1 + array2
print("Додавання", sum_result)

# Поелементне віднімання
subtract_result = array1 - array2
print("Віднімння", subtract_result)

# Поелементне множення
multiply_result = array1 * array2
print("Множення", multiply_result)

Масив 1 [6 3 3 3 4]
Масив 2 [ 6  8 10 10  6]
Додавання [12 11 13 13 10]
Віднімння [ 0 -5 -7 -7 -2]
Множення [36 24 30 30 24]


In [63]:
# (#6) Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

# Розмірність векторів
size = 7

# Створення двох векторів з довільними числами.
vector1 = np.random.rand(size)
vector2 = np.random.rand(size)

# Знаходження скалярного добутку.
dot_product = np.dot(vector1, vector2)

print("Вектор 1", vector1)
print("Вектор 2", vector2)
print("Скалярний добуток: ", dot_product)

Вектор 1 [0.16862586 0.76763651 0.52888992 0.57002132 0.16126324 0.04662008
 0.89127324]
Вектор 2 [0.58675148 0.94449394 0.37226814 0.07857936 0.79533923 0.27726781
 0.85350371]
Скалярний добуток:  1.9675405228780867


In [64]:
# (#7) Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

# Розмірності матриць.
rows1, cols1 = 2, 2
rows2, cols2 = 2, 3

# Створення двох матриць з випадковими цілими числами від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(rows1, rows1))
matrix2 = np.random.randint(1, 11, size=(rows2, rows2))

# Перемноження матриць.
product =np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)

print("Матриця 2:")
print(matrix2)

print("Результат перемноження:")
print(product)

Матриця 1:
[[9 1]
 [3 1]]
Матриця 2:
[[7 7]
 [8 6]]
Результат перемноження:
[[71 69]
 [29 27]]
